# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

def hypertrack_pods
    pod 'HyperTrack.local', :path => '~/hypertrack-ios-v3/HyperTrack.local.podspec'
end

target 'htlive-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  hypertrack_pods
  pod 'PhoneNumberKit', '~> 2.6'
  pod 'MBProgressHUD'
  pod 'Branch'
  pod 'Crashlytics'
  pod 'GRDB.swift', '3.6.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
            config.build_settings['ENABLE_BITCODE'] = 'YES'
	end
    if ['GRDB.swift', 'CocoaLumberjack'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end