# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveLocationSharingStarter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
       pod 'HyperTrack.local', :path => '~/hypertrack-ios-v3/HyperTrack.local.podspec'
       pod 'MBProgressHUD'
  # Pods for LiveLocationSharingStarter

  target 'LiveLocationSharingStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiveLocationSharingStarterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
